# Generated by Django 5.0.14 on 2025-05-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powerbireport',
            options={'ordering': ['name'], 'verbose_name': 'Reporte de Power BI', 'verbose_name_plural': 'Reportes de Power BI'},
        ),
        migrations.AddField(
            model_name='powerbireport',
            name='path',
            field=models.CharField(blank=True, default='', help_text='Ruta completa del reporte en PBIRS (ej: /Carpeta/Subcarpeta/Reporte)', max_length=500, verbose_name='Ruta del Reporte'),
        ),
        migrations.AddField(
            model_name='role',
            name='windows_group',
            field=models.CharField(blank=True, help_text='Ejemplo: DESKTOP-M5D5K4J\\Finanzas o DESKTOP-M5D5K4J\\abastecimiento', max_length=200, verbose_name='Grupo/Usuario Windows/AD'),
        ),
        migrations.AlterField(
            model_name='powerbireport',
            name='roles',
            field=models.ManyToManyField(related_name='reports', to='reports.role', verbose_name='Roles con acceso'),
        ),
    ]
