"""
powerbi_reports/settings.py: Configuración global del proyecto Django.

Este archivo contiene la configuración principal del proyecto de reportes Power BI.
Incluye:
- Configuración básica de Django
- Configuración de base de datos SQL Server
- Integración con Power BI Report Server
- Configuración de autenticación y seguridad
- Configuración de caché y roles

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from django.conf import settings

# =============================================================================
# Configuración de rutas base
# =============================================================================
BASE_DIR = Path(__file__).resolve().parent.parent

# =============================================================================
# Configuración de seguridad y entorno
# =============================================================================
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-here'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# =============================================================================
# Configuración de aplicaciones y middleware
# =============================================================================
INSTALLED_APPS = [
    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Aplicaciones del proyecto
    'reports.apps.ReportsConfig',
    
    # Aplicaciones de terceros
    'crispy_forms',
    'crispy_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# =============================================================================
# Configuración de URLs y templates
# =============================================================================
ROOT_URLCONF = 'powerbi_reports.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'powerbi_reports.wsgi.application'

# =============================================================================
# Configuración de base de datos
# =============================================================================
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'MiBaseDjango',
        'USER': 'SuperUsuario',
        'PASSWORD': 'admin123',
        'HOST': 'DESKTOP-M5D5K4J\\SQLSISREPORTE',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }
}

# =============================================================================
# Configuración de validación de contraseñas
# =============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# =============================================================================
# Configuración de internacionalización
# =============================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# =============================================================================
# Configuración de archivos estáticos
# =============================================================================
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# =============================================================================
# Configuración de campos por defecto
# =============================================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============================================================================
# Configuración de Crispy Forms
# =============================================================================
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# =============================================================================
# Configuración de autenticación
# =============================================================================
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'reports:dashboard'
LOGOUT_REDIRECT_URL = 'login'

# =============================================================================
# Configuración de Power BI
# =============================================================================
# Credenciales de Power BI Service
POWERBI_CLIENT_ID = os.getenv('POWERBI_CLIENT_ID', '')
POWERBI_CLIENT_SECRET = os.getenv('POWERBI_CLIENT_SECRET', '')
POWERBI_TENANT_ID = os.getenv('POWERBI_TENANT_ID', '')

# Configuración del servidor de reportes Power BI
PBIRS_CONFIG = {
    'SERVER_URL': 'http://desktop-m5d5k4j/ReportServer',  # URL del servidor de reportes
    'REPORT_MANAGER_URL': 'http://desktop-m5d5k4j/Reports',  # URL del gestor de reportes
    'USERNAME': 'DESKTOP-M5D5K4J\\reporte_sistema',  # Usuario del servidor
    'PASSWORD': 'admin123',  # Contraseña del servidor
    'DEFAULT_TIMEOUT': 30,  # Tiempo de espera por defecto en segundos
    'VERIFY_SSL': False,  # Verificación SSL desactivada para desarrollo
}

# =============================================================================
# Configuración de caché
# =============================================================================
CACHE_CONFIG = {
    'ENABLED': True,
    'TIMEOUT': 3600,  # Tiempo de caché: 1 hora en segundos
}

# =============================================================================
# Configuración de roles y permisos
# =============================================================================
ROLE_CONFIG = {
    'ADMIN_ROLE': 'PBIRS_Admin',    # Rol de administrador
    'VIEWER_ROLE': 'PBIRS_Viewer',  # Rol de visualizador
    'EDITOR_ROLE': 'PBIRS_Editor',  # Rol de editor
}
